### ISSUE TITLE
Watchers register event listener more than once

### ISSUE THREAD

**Issue by alejandro-mejias** [opentelemetry-php/contrib-auto-laravel#1]
About traces. In a fresh Laravel 10 application, Watcher register methods are executed twice. This assumes that they listen twice for the same event. For example, in the src/QueryWatcher watcher, the register method listens for the Illuminate/Database/Events/QueryExecuted event. Since it runs twice, it doubles the event listener and the traces are recorded duplicates. Look at the attached screenshot.

![Screenshot from 2023-06-02 10-07-57](https://github.com/opentelemetry-php/contrib-auto-laravel/assets/63665312/b6f64b4f-563f-443b-b077-1358a6d0b15c)

You can see listeners `app()[events]->getRawListeners()` and check watchers are duplicated.

**Comment by brettmc** [comment]
Hello. Thanks for the bug report, can you please create it over in our main repo, [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php/issues).

**Comment by brettmc** [comment]
Copied across to main repo, and will disable issues here.
